AUDJPY_H1_GA:
  active_hours: None
  high_length: 1440
  low_length: 60
  mid_length: 480
  prob_bound: 0.075
  size_position: 0.01
  strategy_type: metaga
  symbols:
  - AUDJPY
  tag: metaga_audjpy
  timeframe: mt5.TIMEFRAME_M1
EURUSD_H1_GA:
  active_hours: None
  high_length: 1440
  low_length: 60
  mid_length: 480
  prob_bound: 0.075
  size_position: 0.02
  strategy_type: metaga
  symbols:
  - EURUSD
  tag: metaga_eurusd
  timeframe: mt5.TIMEFRAME_M1
GER40CASH_H1_GA:
  active_hours: None
  high_length: 1440
  low_length: 60
  mid_length: 480
  prob_bound: 0.075
  size_position: 0.02
  strategy_type: metaga
  symbols:
  - GER40
  tag: metaga_dax
  timeframe: mt5.TIMEFRAME_M1
US100CASH_H1_GA:
  active_hours: None
  high_length: 1440
  low_length: 60
  mid_length: 480
  prob_bound: 0.075
  size_position: 0.01
  strategy_type: metaga
  symbols:
  - US100
  tag: metaga_nas
  timeframe: mt5.TIMEFRAME_M1
