BTCUSD_M1_NE:
  active_hours: None
  don_lag: 60
  don_window: 240
  ewma_ewm_span: 15
  long_threshold: 0.015
  lookahead: 30
  ols_window: 120
  rrr: 4
  size_position: 0.0
  strategy_type: metane
  symbols:
  - BTCUSD
  tag: metane_btc
  time_ewm_span: 30
  timeframe: mt5.TIMEFRAME_M5
  tz: UTC
EURUSD_M1_NE:
  active_hours:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  - 18
  - 19
  - 20
  - 21
  - 22
  - 23
  don_lag: 60
  don_window: 240
  ewma_ewm_span: 15
  long_threshold: 0.015
  lookahead: 30
  ols_window: 120
  rrr: 4
  size_position: 0.03
  strategy_type: metane
  symbols:
  - EURUSD
  tag: metane_eurusd
  time_ewm_span: 30
  timeframe: mt5.TIMEFRAME_M5
  tz: UTC
GER40CASH_M1_NE:
  active_hours:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16
  - 18
  - 19
  - 20
  - 21
  - 22
  - 23
  don_lag: 60
  don_window: 240
  ewma_ewm_span: 15
  long_threshold: 0.015
  lookahead: 30
  ols_window: 120
  rrr: 4
  size_position: 0.03
  strategy_type: metane
  symbols:
  - GER40
  tag: metane_dax
  time_ewm_span: 30
  timeframe: mt5.TIMEFRAME_M5
  tz: UTC
US100CASH_M1_NE:
  active_hours: None
  don_lag: 60
  don_window: 240
  ewma_ewm_span: 15
  long_threshold: 0.015
  lookahead: 30
  ols_window: 120
  rrr: 4
  size_position: 0.01
  strategy_type: metane
  symbols:
  - US100
  tag: metane_nas
  time_ewm_span: 30
  timeframe: mt5.TIMEFRAME_M5
  tz: UTC
