AUDJPY_H1:
  active_hours:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 16
  - 18
  - 19
  - 20
  - 21
  - 22
  - 23
  limit_number_position: 5
  size_position: 0.02
  strategy_type: metafvg
  symbols:
  - AUDJPY
  tag: metafvg_audjpy
  timeframe: mt5.TIMEFRAME_M1
EURUSD_H1:
  active_hours: None
  limit_number_position: 5
  size_position: 0.03
  strategy_type: metafvg
  symbols:
  - EURUSD
  tag: metafvg_eurusd
  timeframe: mt5.TIMEFRAME_M1
GER40CASH_H1_GA:
  active_hours:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 9
  - 10
  - 11
  - 12
  - 13
  - 15
  - 16
  - 17
  - 18
  - 19
  - 20
  - 21
  - 22
  - 23
  limit_number_position: 5
  size_position: 0.03
  strategy_type: metafvg
  symbols:
  - GER40
  tag: metafvg_dax
  timeframe: mt5.TIMEFRAME_M1
US100CASH_H1_GA:
  active_hours: None
  limit_number_position: 5
  size_position: 0.01
  strategy_type: metafvg
  symbols:
  - US100
  tag: metafvg_nas
  timeframe: mt5.TIMEFRAME_M1
