AUDJPY_H1_GO:
  active_hours: None
  lookahead: 48
  mean_rev_tf: monthly
  risk_factor: 0.0001
  size_position: 0.01
  strategy_type: metago
  symbols:
  - AUDJPY
  tag: metago_audjpy
  timeframe: mt5.TIMEFRAME_H1
AUDJPy_H1_WEEKLY:
  active_hours: None
  lookahead: 48
  mean_rev_tf: weekly
  risk_factor: 0.0001
  size_position: 0.01
  strategy_type: metago
  symbols:
  - AUDJPY
  tag: metago_w_audjpy
  timeframe: mt5.TIMEFRAME_H1
EURNOK_H1_GO:
  active_hours: None
  lookahead: 48
  mean_rev_tf: monthly
  risk_factor: 0.0001
  size_position: 0.0
  strategy_type: metago
  symbols:
  - EURNOK
  tag: metago_enok
  timeframe: mt5.TIMEFRAME_H1
EURUSD_H1_GO:
  active_hours: None
  lookahead: 48
  mean_rev_tf: monthly
  risk_factor: 0.0001
  size_position: 0.04
  strategy_type: metago
  symbols:
  - EURUSD
  tag: metago_eurusd
  timeframe: mt5.TIMEFRAME_H1
EURUSD_H1_WEEKLY:
  active_hours: None
  lookahead: 48
  mean_rev_tf: weekly
  risk_factor: 0.0001
  size_position: 0.04
  strategy_type: metago
  symbols:
  - EURUSD
  tag: metago_weekly_eur
  timeframe: mt5.TIMEFRAME_H1
USDCAD_H1_GO:
  active_hours: None
  lookahead: 48
  mean_rev_tf: monthly
  risk_factor: 0.0001
  size_position: 0.03
  strategy_type: metago
  symbols:
  - USDCAD
  tag: metago_usdcad
  timeframe: mt5.TIMEFRAME_H1
USDCHF_H1_GO:
  active_hours: None
  lookahead: 48
  mean_rev_tf: monthly
  risk_factor: 0.0001
  size_position: 0.04
  strategy_type: metago
  symbols:
  - USDCHF
  tag: metago_usdchf
  timeframe: mt5.TIMEFRAME_H1
USDJPY_H1_GO:
  active_hours: None
  lookahead: 48
  mean_rev_tf: monthly
  risk_factor: 0.0001
  size_position: 0.01
  strategy_type: metago
  symbols:
  - USDJPY
  tag: metago_usdjpy
  timeframe: mt5.TIMEFRAME_H1
USDNOK_H1_GO:
  active_hours: None
  lookahead: 48
  mean_rev_tf: monthly
  risk_factor: 0.0001
  size_position: 0.01
  strategy_type: metago
  symbols:
  - USDNOK
  tag: metago_unok
  timeframe: mt5.TIMEFRAME_H1
USDZAR_H1_GO:
  active_hours: None
  lookahead: 48
  mean_rev_tf: monthly
  risk_factor: 0.0001
  size_position: 0.01
  strategy_type: metago
  symbols:
  - USDZAR
  tag: metago_usdzar
  timeframe: mt5.TIMEFRAME_H1
USDZAR_H1_WEEKLY:
  active_hours: None
  lookahead: 48
  mean_rev_tf: weekly
  risk_factor: 0.0001
  size_position: 0.01
  strategy_type: metago
  symbols:
  - USDZAR
  tag: metago_weekly_zar
  timeframe: mt5.TIMEFRAME_H1
