AUDCHF_H1_MLP:
  strategy_type: metamlp
  symbols: [AUDCHF]
  timeframe: mt5.TIMEFRAME_H1
  tag: metamlp_audchf
  size_position: 0.05
  active_hours: None
  rolling_windows: [24, 120, 528]
  thresholds: [-7.0, -5.0, -1.0, 1.0, 5.0, 7.0]
  horizons: [4, 8, 10, 12]
  hidden_layers: [64, 32]
  max_iter: 500
  fit_lookback_days: 1460
  train_ratio: 0.9
  risk_reward: 1.10
